FROM golang:1.21-alpine as builder

WORKDIR /app

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o wow-client cmd/client/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder  /app/wow-client .

# Copy ENV file, NOT recommended, just for FAST running in test assignment
COPY --from=builder  /app/.env_client .

CMD ["./wow-client"]
